### ISSUE TITLE
Mac OS symfony server timeouts with liipimagine bundle - mozjpeg

### ISSUE THREAD

**Issue by plamenh** [liip/LiipImagineBundle#1137] opened 2018-11-08 10:40 UTC
Running dev environment on mac os with symfony 4 and launching bin/console server:start; Whenever cache resolution is attempted, the server hangs; resolving through console returns timeout.

mozjpeg is installed with brew.

### Preconditions

1. Symfony 4 console server running on mac os
2. mozjpeg installed via brew

### Steps to reproduce

1. Open url with liip image
2. Server hangs
3. Timeout

### Expected result

1. Cache should properly resolve

### Actual result

1. ![screenshot 2018-11-08 at 12 37 03](https://user-images.githubusercontent.com/14073311/48193541-599c3400-e353-11e8-8c47-c2dc42b27182.png)

**Comment by geri777** [comment] 2019-08-17 23:03
I have the same problem on Windows (Apache, PHP 7.2.7)

**Comment by franmomu** [comment] 2019-09-01 13:31
Did you manage to solve it? It could be that the path to `cjpeg` is wrong, in my case (installed with brew as well) is in `/usr/local/opt/mozjpeg/bin/cjpeg`

**Comment by plamenh** [comment] 2019-09-01 14:31
Gave up a long time ago, just disabled filters in the dev environment.

**Comment by dbu** [comment] 2019-09-02 06:25
not sure if that is the cause here, but when running the php built-in webserver (like the symfony console thing afaik does) then php is single threaded, meaning that if the server process does a http call on itself, it will hang forever/until timeout.

anyways, closing this as you found a workaround.

**Closed by dbu** 2019-09-02 06:25 UTC
