### ISSUE TITLE
How to resolve by stream?

### ISSUE THREAD

**Issue by garak** [liip/LiipImagineBundle#592] opened 2015-04-14 12:53 UTC
I'm using LiipImagineBundle with Gaufrette.
Gaufrette is configured to use aws S3, so I configured a StreamLoader. So far so good.
Now the problem is that I'm not able to resolve thumbnails via Gaufrette, since the only way I found here is AwsS3Resolver, that is not what I want: AwsS3Resolver bypasses Gaufrette and so I cannot use Gaufrette options (most notably the "directory" options), but the worst point is that this completely defeats the Gaufrette abstraction layer (e.g. I cannot easily switch between filesystem abstractions).
So, is a stream resolver really missing here, or am I doing something wrong?
Thanks in advance.

**Comment by makasim** [comment] 2015-04-14 13:13
We can introduce a gaufrette resolver. Sounds reasonable to me.

**Comment by romaricdrigon** [comment] 2015-04-30 14:30
+1 for a Gaufrette resolver.
Using stream feels like a step back from the Symfony2 style.

**Comment by makasim** [comment] 2015-05-07 10:13
any takers on this?

**Comment by garak** [comment] 2015-05-07 11:20
I tried to write something myself, and I ended up with some code. But my main issue is how to get the asbtraction work with every implementation. So, I implemented my GaufreffeResolver, but in the ``resolve`` method I have to call ``$this->filesystem->getAdapter()->getUrl()``, but unfortunately ``getUrl()`` is not present in every adapter. I'm stuck at this point.

**Comment by makasim** [comment] 2015-05-07 17:38
I see, it is hard to use gaufrette as a resolver. but can at least use it as a data loader, would it be useful?

**Comment by romaricdrigon** [comment] 2015-06-16 06:39
Why closing it, something was done?

**Comment by makasim** [comment] 2015-06-16 06:40
The interface of a resolver is richer than stream can provide us with. So nothing to do here. The stream data loader is already here.

**Comment by romaricdrigon** [comment] 2015-06-16 06:43
I think the issue is about working with Gaufrette by stream, and not by using objects provided by Gaufrette.
At least it is what I understood from the first post. And I can hardly see a stream having a better interface than a Gaufrette filesystem object.

**Comment by makasim** [comment] 2015-06-16 06:49
The PR is very welcome, I dont see much sense keeping it open, since it is just an addition which is not block us in any way.

**Comment by makasim** [comment] 2015-06-16 06:49
The PR is very welcome (:

**Comment by romaricdrigon** [comment] 2015-06-16 06:50
Well, if someone wants to have some time on it, the issue keeps track of it. For instance for some Symfony hack day.

**Comment by michellesanver** [comment] 2019-10-04 09:43
This needs an issue with a more clear description of the feature and the requested implementation. Create a new issue with clarifications, link this one, and close when done :)

**Closed** 2021-10-06 07:51 UTC
Labels: Level: New Feature 🆕, State: Need To Investigate 🔎
