### ISSUE TITLE
avif support

### ISSUE THREAD

**Issue by tacman** [liip/LiipImagineBundle#1585] opened 2024-05-28 23:45 UTC
I saw this article today about avif format today and since virtually all of my images are served through this bundle, I figured I'd at least ask if avif is supported.

https://levelup.gitconnected.com/unveiling-avif-the-next-gen-web-image-standard-forget-about-webp-e6c5857be528

Thx.

**Comment by dbu** [comment] 2024-05-29 06:05
interesting. would be another scenario like `webp` where we need to detect the capability and serve a different file depending on capability. afaik the webp support has beeen a bit confusing - might be something to revisit at the same time, to generalize the concept of using different formats based on client capability (this conflicts strongly with embedding the path to the cached image into the html when the html gets cached by some http level cache - we would then need to vary on the headers used to detect the webp/avif capabilities. afaik this is not currently solved well. one option could be to use the controller path for the image, but have a flag to force returning the filesystem path along with documentation to only do this when either no http caching is allowed or a `vary` header on the relevant request header is configured (and document how to cleanup that request header to avoid unnecessary variants))

a first step would be to check if imagine / gd support avif or if we would need a separate tool for it. and then to expand the capabilities selection system.

i added this to the 3.0 milestone to remind us we should challenge this topic

**Comment by hockdudu** [comment] 2024-06-05 17:01
There's already an issue for AVIF: https://github.com/liip/LiipImagineBundle/issues/1314

**Comment by dbu** [comment] 2024-06-06 05:55
@hockdudu thanks for pointing this out. i will close this ticket as duplicate of #1314

**Closed as completed by dbu** 2024-06-06 05:55 UTC
