### ISSUE TITLE
Auto rotate problem in real server

### ISSUE THREAD

**Issue by jekeyeke** [liip/LiipImagineBundle#741] opened 2016-05-27 13:01 UTC
Hi everyone.

I have a problem with auto_rotate option.
In local, it works perfect but when I upload the code to the real server, the auto_rotate option doesn't work.
I'm working with Symfony and i don't know which is the problem.

This is my code:

```
liip_imagine:
    driver: gd
    cache:  default
    data_loader:   default

    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web
                cache_prefix: media/images/cache
    filter_sets:
        original:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [1200, 1200], mode: inset }
```

I appreciate any help.

Thanks

**Comment by BartVB** [comment] 2016-07-12 18:25
If this is working locally and not on the server then chances are that you're using an outdated version of GD on the server. Could you check the versions?

BTW any particular reason why you are using GD and not one of the other libs?

**Comment by davidromani** [comment] 2016-07-14 14:39
Same problem here.

Working local machine (OSX 10.10 + PHP 5.6.19) config:
```
$ php -i | grep -i --color gd
GD Support => enabled
GD Version => bundled (2.1.0 compatible)
gd.jpeg_ignore_warning => 0 => 0
```

**Not working** server machine (Ubuntu 14.04 + PHP 5.5.9) config:
```
GD Support => enabled
GD Version => 2.1.1-dev
gd.jpeg_ignore_warning => 0 => 0
```

**Comment by lsmith77** [comment] 2016-07-18 07:58
Yeah I think this is more likely a GD issue.

https://twitter.com/PierreJoye/status/754939618982699008
"@lsmith some cases have been improved in 2.2, and quality much better in master.
Please try using libgd master. Ideally open an issue there"

can you contact the GD maintainers about this?

**Comment by lsmith77** [comment] 2016-07-18 08:00
if someone can setup a reproduce-able test case Pierre offered to have a look

**Comment by jekeyeke** [comment] 2016-08-08 14:07
Hi everyone,
@BartVB when i started in the project, liip was already installed so i continued since there.

Working local machine (Ubuntu 14 + PHP 5.5.9) config:
```
$ php -i | grep -i --color gd
GD Support => enabled
GD Version => bundled (2.1.0 compatible)
gd.jpeg_ignore_warning => 0 => 0
```

Not working server machine (Debian 3.2.68 + PHP 5.5.25) config:

```
GD Support => enabled
GD Version => bundled (2.1.0 compatible)
gd.jpeg_ignore_warning => 0 => 0
```

Could you tell me another lib to use?

Thanks

**Comment by antoligy** [comment] 2016-08-08 14:45
Is ImageMagick or GraphicsMagick an option?

**Comment by jekeyeke** [comment] 2016-08-09 10:29
Hi again,

@antoligy i tried both and got the same result. Perfect in local but wrong in server.

Libs on server machine

```
imagick
imagick module => enabled
imagick module version => 3.4.3RC1
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator
Imagick compiled with ImageMagick version => ImageMagick 6.7.7-10 2014-03-08 Q16 http://www.imagemagick.org
Imagick using ImageMagick library version => ImageMagick 6.7.7-10 2016-04-07 Q16 http://www.imagemagick.org
imagick.locale_fix => 0 => 0
imagick.progress_monitor => 0 => 0
imagick.skip_version_check => 0 => 0
```

```
gmagick
gmagick module => enabled
gmagick version => 1.1.7RC3
```

Anyone has other idea?

Thanks

**Comment by jehaby** [comment] 2016-08-09 14:07
Can you show exif.Orientation key in original and resulted image. I have troubles with auto_rotate filter when there wasn't any other filter after it which stripped exif info on an image. Thumbnail filter should do it, but maybe there's something wrong with your server app parameters (cache without thumbnail filter? ).

**Comment by MathieuThiry** [comment] 2017-02-06 21:55
Same problem here :(

Any news about this issue ?

Working local : PHP/5.5.12
```
GD Support => enabled
GD Version => bundled (2.1.0 compatible)
gd.jpeg_ignore_warning => 0 => 0
```

Not working server : PHP/7.1.0
```
GD Support => enabled
GD Version => bundled (2.1.0 compatible)
gd.jpeg_ignore_warning => 0 => 0
```

**Comment by robfrawley** [comment] 2017-02-06 23:22
@MathieuThiry We can't really diagnose this further without a reproducible system made available to us. If this is a VM, can you clone it and offer access to the clone for a short window? You can contact me via `github AT robfrawley DOT com`. Otherwise, I don't know what we can do...

**Comment by michellesanver** [comment] 2019-10-04 08:13
Closing this issue because of #1230

More details: https://github.com/liip/LiipImagineBundle/pull/1230#issuecomment-537934662

If it's still an issue for you, please open a new issue, and thanks a lot :)

**Closed by michellesanver** 2019-10-04 08:13 UTC
Labels: stat: confirmed
