### ISSUE TITLE
Scale filter not found / incorrect filter config documentation

### ISSUE THREAD

**Issue by ktrzos** [liip/LiipImagineBundle#818] opened 2016-10-30 19:56 UTC
http://symfony.com/doc/master/bundles/LiipImagineBundle/filters/sizing.html#scale

```
parameters:
    images_quality: 80

liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: images/thumb

    filter_sets:
        cache: ~
        news_image:
            quality: '%images_quality%'
            filters:
                scale: { dim: [ 1000, 666 ] }
```

AAaaaaaaand it's not working. Returning error:

> Could not find filter loader for "scale" filter type 

Why documentation is writing about something that is not working???

And, when I'm adding `-` character before `scale: { dim: [ 1000, 666 ] }` (based on documentation from Symfony.com), error occurs:

> The attribute "name" must be set for path "liip_imagine.filter_sets.news_image.filters".

Where is the most updated documentation for this bundle...?

**Comment by robfrawley** [comment] 2016-10-30 22:12
@ktrzos The most updated documentation is the website you liked to, hosted on the official Symfony docs. As for the _scale_ filter, it was added _after_ the last stable release, so you will need to set you composer version constraint to `dev-master` for now if you'd like to use it.

As for the configuration format issue you mentioned, I will look into that further shortly.

**Comment by robfrawley** [comment] 2016-10-30 23:46
@ktrzos Documentation changes have been pushed to address the error you pointed out. It should be available in the [generated, online docs](http://symfony.com/doc/master/bundles/LiipImagineBundle/filters/sizing.html#scale) shortly; the compilation of them are automatic and quick).

If this and my previous answer resolve your issue, please close this.

**Closed** 2016-10-30 23:57 UTC
Labels: documentation, verified

**Comment by robfrawley** [comment] 2016-10-31 16:24
@ktrzos I accidentally closed this; I generally prefer that the person who opened it closes it as a confirmation that the issue is solved. Please re-open if this is not the case. Thanks!

**Comment by ktrzos** [comment] 2016-11-02 09:14
Not a problem :). It's all ok now... I think :D. Thanks for help!
