### ISSUE TITLE
imagine-bundle configuration:  "A tree builder without a root node is deprecated since Symfony 4.2"

### ISSUE THREAD

**Issue by greenphp** [liip/LiipImagineBundle#1164] opened 2019-03-18 21:42 UTC
### Preconditions

Symfony 4.2 shows deprecated message in Symfony Profiler

`A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.`

caused in` \vendor\liip\imagine-bundle\DependencyInjection\Configuration.php:48`

### Steps to reproduce

Symfony 4.2, open "Symfony Profiler" -> Log Messages -> Deprecations

### Detailed output

```
A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.
Hide context    Hide trace
[
  "exception" => SilencedErrorContext {#107 }
]
{
  C:\symfony-project\vendor\symfony\config\Definition\Builder\TreeBuilder.php:30 {}
  C:\symfony-project\vendor\liip\imagine-bundle\DependencyInjection\Configuration.php:48 {
    › {
    ›     $treeBuilder = new TreeBuilder();
    ›     $rootNode = $treeBuilder->root('liip_imagine', 'array');
  }
}
```

**Comment by endelwar** [comment] 2019-04-02 09:07
This has been fixed in commit bf50bf9764b6c299fbd0af648671614e403a95c2

@robfrawley @maximgubar it would be nice to have a 2.1.1 release tagged from commit 164b4dd, what do you think?

**Comment by mikemix** [comment] 2019-04-19 06:36
Push new release please.

**Comment by cybernet** [comment] 2019-06-21 18:03
any news on the release ?

**Comment by thomas2411** [comment] 2019-06-29 10:34
I wonder if there are any maintainers here?

**Comment by cybernet** [comment] 2019-06-29 10:38
so do I ...

**Comment by maximgubar** [comment] 2019-06-29 11:49
@lsmith77 I dont have time atm, could you ping liipers?

**Comment by OlivierToussaint** [comment] 2019-07-10 16:05
Thank for your work !

When you have a little time, it would be great to have a new version. 🥳🤗

**Comment by dbu** [comment] 2019-08-22 06:46
we are trying to wrap up things and get a release out by the end of august. closing this issue as a duplicate of #1186

**Closed by dbu** 2019-08-22 06:46 UTC
