### ISSUE TITLE
Pre and Post store events

### ISSUE THREAD

**Issue by loevgaard** [liip/LiipImagineBundle#1126] opened 2018-08-31 12:24 UTC
**Is your feature request related to a problem? Please describe.**
I use LiipImagineBundle with Sylius and need to update the product entity when an image is stored, but right now I have to do that using filters or post processors, which is kind of a hacky way to do it.

**Describe the solution you'd like**
Wrap this line: https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Cache/CacheManager.php#L218 with `PRE_STORE` and `POST_STORE` events.

**Comment by dbu** [comment] 2021-10-28 08:08
duplicate of #1280

**Closed as completed by dbu** 2021-10-28 08:08 UTC
Labels: Level: New Feature 🆕
