### ISSUE TITLE
Webp generation broken

### ISSUE THREAD

**Issue by 7system7** [liip/LiipImagineBundle#1409] opened 2021-10-29 11:03 UTC
With webp settings nothing happening. It generates jpg only.

### Preconditions

1. PHP 7.4, GD 2.3.0, Imagick 3.5.1, Symfony 5.3.10
2. Liip bundle version: 2.7.0

### Steps to reproduce

1. Install bundle and setup
```yaml
    driver: "gd" # I tried this w/ imagick also but that was not worked also.
    resolvers:
        default:
            web_path: ~
    controller:
        redirect_response_code: 302
    webp:
        generate: true
    filter_sets:
        cache: ~
        thumbnail_big:
            quality: 75
            filters:
                thumbnail: { size: [ 800, 450 ], mode: inset }
                background: { size: [ 800, 450 ], position: center, color: '#000000' }
        thumbnail_small:
            quality: 50
            format: webp
            filters:
                thumbnail: { size: [ 90, 50 ], mode: inset }
                background: { size: [ 90, 50 ], position: center, color: '#000000' }
```
2. Upload `jpg` images to the system.
3. Use resolver
```php
use Liip\ImagineBundle\Imagine\Cache\CacheManager;
use Liip\ImagineBundle\Imagine\Data\DataManager;
use Liip\ImagineBundle\Imagine\Filter\FilterManager;

...

    private const BIG_FILTER   = 'thumbnail_big';
    private const SMALL_FILTER = 'thumbnail_small';

    public function __construct(
        DataManager $dataManager,
        FilterManager $filterManager,
        CacheManager $cacheManager
    ) { ... }

...

        $urlBig = $this->cacheManager->isStored($path, self::BIG_FILTER)
            ? $this->cacheManager->resolve($path, self::BIG_FILTER)
            : $this->generateUrl(self::BIG_FILTER, $path);

        $urlSmall = $this->cacheManager->isStored($path, self::SMALL_FILTER)
            ? $this->cacheManager->resolve($path, self::SMALL_FILTER)
            : $this->generateUrl(self::SMALL_FILTER, $path);

...

    private function generateUrl(string $filter, string $picPath): string
    {
        $image = $this->dataManager->find($filter, $picPath);
        $image = $this->filterManager->applyFilter($image, $filter);
        $this->cacheManager->store($image, $picPath, $filter);
        return $this->cacheManager->resolve($picPath, $filter);
    }
```

### Expected result

As I know from documentation, by default there should be `.webp` images next to the `.jpg` because the 
```yaml
webp:
        generate: true
```
option. The `thumbnail_small` filter should only generate webps for thumbnails.

```console
public/media/cache
├── thumbnail_big
│   └── media
│       └── news
│           ├── 1vpWGn-609c1ca783d243.72915944.jpg
│           ├── 1vpWGn-609c1ca783d243.72915944.webp
│           ├── ALkpaA-609cd51b0afa45.56825315.jpg
│           ├── ALkpaA-609cd51b0afa45.56825315.webp
│           ├── ZPQNzq-609c1c99ee1932.95451227.jpg
│           └── ZPQNzq-609c1c99ee1932.95451227.webp
└── thumbnail_small
    └── media
        └── news
            ├── 1vpWGn-609c1ca783d243.72915944.webp
            ├── ALkpaA-609cd51b0afa45.56825315.webp
            └── ZPQNzq-609c1c99ee1932.95451227.wepb
```

### Actual result

The generated files are
```console
public/media/cache
├── thumbnail_big
│   └── media
│       └── news
│           ├── 1vpWGn-609c1ca783d243.72915944.jpg
│           ├── ALkpaA-609cd51b0afa45.56825315.jpg
│           └── ZPQNzq-609c1c99ee1932.95451227.jpg
└── thumbnail_small
    └── media
        └── news
            ├── 1vpWGn-609c1ca783d243.72915944.jpg
            ├── ALkpaA-609cd51b0afa45.56825315.jpg
            └── ZPQNzq-609c1c99ee1932.95451227.jpg
```

**Comment by dbu** [comment] 2021-10-29 11:13
is this fixed by #1408?

**Comment by mynameisbogdan** [comment] 2021-10-29 11:32
@dbu I don't think it related to that PR. Maybe it's related to the new format extension resolver?

**Comment by dbu** [comment] 2021-10-29 11:53
I should have released a beta version first :-(

@7system7 have you tried requesting with a browser that asks for webp? or does it "only" happen when pre-warming the cache?

i have an extremly busy weekend ahead, please lock your dependency to version 2.6 until we can fix it next week.

**Comment by 7system7** [comment] 2021-10-29 12:14
@dbu It is OK, thank you for your quick response. I tried this before/after warmup, w/ cache, w/o cache. Nothing worked from browser. None w/ 2.7.x, nor w/ 2.6.x. Everything else is cool, except the webp generation.

Actually I tried the **resolve** from terminal, w/ the command, but it does not work too for me.

### Command

```console
$ bin/console liip:imagine:cache:resolve /var/www/<project-dir>/public/media/news/*
```

### Result

```console
                                                                                                                        
 [liip/imagine-bundle] liip:imagine:cache:resolve                                                                       
                                                                                                                        

 - /var/www/<project-dir>/public/media/news/1vpWGn-609c1ca783d243.72915944.jpg[cache] (failed) Source image not resolvable "/var/www/<project-dir>/public/media/news/1vpWGn-609c1ca783d243.72915944.jpg" in root path(s) "/var/www/<project-dir>/public"
 - /var/www/<project-dir>/public/media/news/1vpWGn-609c1ca783d243.72915944.jpg[thumbnail_big] (failed) Source image not resolvable "/var/www/<project-dir>/public/media/news/1vpWGn-609c1ca783d243.72915944.jpg" in root path(s) "/var/www/<project-dir>/public"
 - /var/www/<project-dir>/public/media/news/1vpWGn-609c1ca783d243.72915944.jpg[thumbnail_small] (failed) Source image not resolvable "/var/www/<project-dir>/public/media/news/1vpWGn-609c1ca783d243.72915944.jpg" in root path(s) "/var/www/<project-dir>/public"
 - /var/www/<project-dir>/public/media/news/ALkpaA-609cd51b0afa45.56825315.jpg[cache] (failed) Source image not resolvable "/var/www/<project-dir>/public/media/news/ALkpaA-609cd51b0afa45.56825315.jpg" in root path(s) "/var/www/<project-dir>/public"
 - /var/www/<project-dir>/public/media/news/ALkpaA-609cd51b0afa45.56825315.jpg[thumbnail_big] (failed) Source image not resolvable "/var/www/<project-dir>/public/media/news/ALkpaA-609cd51b0afa45.56825315.jpg" in root path(s) "/var/www/<project-dir>/public"
 - /var/www/<project-dir>/public/media/news/ALkpaA-609cd51b0afa45.56825315.jpg[thumbnail_small] (failed) Source image not resolvable "/var/www/<project-dir>/public/media/news/ALkpaA-609cd51b0afa45.56825315.jpg" in root path(s) "/var/www/<project-dir>/public"
 - /var/www/<project-dir>/public/media/news/ZPQNzq-609c1c99ee1932.95451227.jpg[cache] (failed) Source image not resolvable "/var/www/<project-dir>/public/media/news/ZPQNzq-609c1c99ee1932.95451227.jpg" in root path(s) "/var/www/<project-dir>/public"
 - /var/www/<project-dir>/public/media/news/ZPQNzq-609c1c99ee1932.95451227.jpg[thumbnail_big] (failed) Source image not resolvable "/var/www/<project-dir>/public/media/news/ZPQNzq-609c1c99ee1932.95451227.jpg" in root path(s) "/var/www/<project-dir>/public"
 - /var/www/<project-dir>/public/media/news/ZPQNzq-609c1c99ee1932.95451227.jpg[thumbnail_small] (failed) Source image not resolvable "/var/www/<project-dir>/public/media/news/ZPQNzq-609c1c99ee1932.95451227.jpg" in root path(s) "/var/www/<project-dir>/public"

 #                                                                                                                      
 # [ERROR] Completed 0 resolutions (3 images, 3 filters) [encountered 9 failures]                                       
 #                                                                                                                      
```

### Symfony log

```console
[2021-10-29T14:13:23.692071+02:00] console.DEBUG: Command "liip:imagine:cache:resolve '/var/www/<project-dir>/public/media/news/1vpWGn-609c1ca783d243.72915944.jpg' '/var/www/<project-dir>/public/media/news/ALkpaA-609cd51b0afa45.56825315.jpg' '/var/www/<project-dir>/public/media/news/ZPQNzq-609c1c99ee1932.95451227.jpg'" exited with code "255" {"command":"liip:imagine:cache:resolve '/var/www/<project-dir>/public/media/news/1vpWGn-609c1ca783d243.72915944.jpg' '/var/www/<project-dir>/public/media/news/ALkpaA-609cd51b0afa45.56825315.jpg' '/var/www/<project-dir>/public/media/news/ZPQNzq-609c1c99ee1932.95451227.jpg'","code":255} []
```

**Comment by mynameisbogdan** [comment] 2021-10-29 12:33
@7system7 using this [resolver](https://symfony.com/bundles/LiipImagineBundle/2.x/cache-resolver/format_extension.html) changes anything? 

For me it does when I'm using `format: webp` under a filter set. I don't understand why this resolver was made opt-in anyways.

**Comment by 7system7** [comment] 2021-11-01 18:00
I will try it tomorrow. :)

**Comment by dbu** [comment] 2021-11-02 10:51
did this work with version 2.6? if it did, we have a BC break somewhere, but i don't think it would have worked.

afaik, you need to explictly tell to generate the webp variant.

in verison 2.7, we introduced FilterService::warmupCache. this is used by the ResolveCacheCommand as well as symfony messenger WarmupCacheHandler. if i understand correctly, this is what you want to do. you could inject the filter service and call warmup on it, or use [symfony messenger](https://symfony.com/doc/current/LiipImagineBundle/optimizations/resolve-cache-images-in-background.html#symfony-messenger)

**Comment by mynameisbogdan** [comment] 2021-11-02 11:48
It tested it with 2.6.1 and 2.7.1 and it doesn't seem to be a BC break. The only caveat is that without `FormatExtensionResolver` the desired format with be saved with the original extension, so for example png/webp saved with a jpg extension. 

If you're using `webp.generate: true` and `default_filter_set_settings.format: png` for a jpeg image you'll have a `.png` and a `.jpg.png` for the webp image, so somewhere it's still an issue with the extension.

Without `FormatExtensionResolver` it saves the webp as `.jpg.webp`.

**Comment by dbu** [comment] 2021-11-03 07:38
thanks for testing. does that problem happen with both 2.6.1 and 2.7.1, or only in 2.7.1?

**Comment by mynameisbogdan** [comment] 2021-11-03 09:00
Both versions, but `FormatExtensionResolver` is new in 2.7.

**Comment by dbu** [comment] 2021-11-03 09:23
ok, thanks. at least not a regression then :see_no_evil: 

i wonder if it would be considered a BC break if we fix that. 

this is not really the subject of the OP i think. can you create a new issue that describes the problem? or maybe even propose a way to fix it?

**Comment by 7system7** [comment] 2022-03-07 08:25
Any update on this? :cry:

**Comment by dbu** [comment] 2022-03-07 08:34
if somebody has to be time to investigate and propose a fix, i am happy to review it, but i don't have time to dig into it.

**Comment by 7system7** [comment] 2022-03-07 08:56
I do not have time neither, sorry. But, if anyone facing this issue, there is [another bundle](https://github.com/codebuds33/webp-conversion-bundle) for that. It works by itself, and it can be used w/ this bundle.

**Comment by mareckigit** [comment] 2023-02-24 16:15
1. If you want to use `format: webp`, remove from config `webp: generate: true` , because it's enforces the use  "resolve" URL to detect if browser supports WebP and then provides relevant files.
2. Use this [FormatExtensionResolver](https://symfony.com/bundles/LiipImagineBundle/2.x/cache-resolver/format_extension.html) to fix problem with extensions. Without this Imagine with `format: webp` generetes webp files but keeps original extension.

Tested on version 2.10.0

**Closed as completed** 2023-02-24 22:27 UTC
