### ISSUE TITLE
Artifacts in pictures

### ISSUE THREAD

**Issue by peter-gribanov** [liip/LiipImagineBundle#1086] opened 2018-04-23 14:37 UTC
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | no
| BC Break Report? | no
| RFC? | no
| Imagine Bundle Version | 1.9.1

```yml
# liip_imagine.yml
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/web'
                cache_prefix: 'media/suit'
    loaders:
        default:
            filesystem:
                data_root: '%liip_imagine.data_root%'
    filter_sets:
        product_cover_card:
            quality: 75
            filters:
                scale: { dim: [937, 600] }
```

There are very strange artifacts in the pictures.

![1021716637.jpg](https://user-images.githubusercontent.com/1954436/39131571-71fa3ccc-4718-11e8-9947-9c698e3f5205.jpg)

It all started with the fact that we have some of the pictures, it's PNG and for optimization we decided to convert them to JPEG.

```yml
liip_imagine:
    filter_sets:
        product_cover_card:
            quality: 75
            format: jpg # change format
            filters:
                scale: { dim: [937, 600] }
```

This led to very strange artifacts.

![1517913174009854_Angry_Birds.jpg](https://image.ibb.co/nEkE6x/1517913174009854_Angry_Birds.jpg)

Since the problem is clearly due to the transparent background, i just added a white background to the filter:

```yml
liip_imagine:
    filter_sets:
        product_cover_card:
            quality: 75
            format: jpg # change format
            filters:
                background: { color: '#ffffff' } # white bg
                scale: { dim: [937, 600] }
```

This fixed PNG, but broke JPEG files:

![1014527184 (1).jpg](https://i.imgur.com/EQIg10L.jpg)

I use GD only

```
$ php -v
PHP 7.2.4-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:53:57) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.4-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

```
$ php --ri gd

gd

GD Support => enabled
GD headers Version => 2.2.5
GD library Version => 2.2.5
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.6.1
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 8
PNG Support => enabled
libPNG Version => 1.2.54
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled
WebP Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1
```

Interestingly, bug appears with a "thumbnail" filter.
With other filters this bug is not seen yet.

**Comment by peter-gribanov** [comment] 2019-01-24 10:19
The problem is still relevant.
The problem is still with the `thumbnail` filter.

### Origin

<details>
  <summary>PNG</summary>
<img src="https://user-images.githubusercontent.com/1954436/51619970-7bfd2100-1f42-11e9-83ff-7df336a59b9a.png">
</details>

<details>
  <summary>JPEG</summary>
<img src="https://user-images.githubusercontent.com/1954436/51620351-3ab94100-1f43-11e9-9e6d-8d0eb4dfa9b8.jpg">
</details>

## Only thumbnail

```yaml
liip_imagine:
    filter_sets:
        preview:
            quality: 80
            format: jpg # change format
            filters:
                thumbnail: { size: [300, 300], mode: inset }
```
### Result

<details>
  <summary>PNG</summary>
<img src="https://user-images.githubusercontent.com/1954436/51618105-a816a300-1f3e-11e9-9110-2a8bcbcf436f.png">
</details>

<details>
  <summary>JPEG</summary>
<img src="https://user-images.githubusercontent.com/1954436/51620388-5290c500-1f43-11e9-832b-2f4c02e284fb.jpg">
</details>

## thumbnail with white background

```yaml
liip_imagine:
    filter_sets:
        preview:
            quality: 80
            format: jpg # change format
            filters:
                background: { color: '#ffffff' } # white bg
                thumbnail: { size: [300, 300], mode: inset }
```
### Result

<details>
  <summary>PNG</summary>
<img src="https://user-images.githubusercontent.com/1954436/51664263-1f454900-1fca-11e9-9794-4181fdb0ee8c.png">
</details>

<details>
  <summary>JPEG</summary>
<img src="https://user-images.githubusercontent.com/1954436/51664281-29ffde00-1fca-11e9-973a-2d7ed980be2c.png">
</details>

### Some fix

Add background after resizeng image.
This method works, but the result will not be a reduced preview with aspect ratio. The result a picture with a fixed size. Therefore, it is better to use a `fixed-size` filter in this case.

```yaml
liip_imagine:
    filter_sets:
        preview:
            quality: 80
            format: jpg # change format
            filters:
                thumbnail: { size: [300, 300], mode: inset }
                background: { color: '#ffffff' } # white bg
```
### Result

<details>
  <summary>PNG</summary>
<img src="https://user-images.githubusercontent.com/1954436/51671100-3c354880-1fd9-11e9-8c01-7057ed03b427.png">
</details>

<details>
  <summary>JPEG</summary>
<img src="https://user-images.githubusercontent.com/1954436/51671155-5707bd00-1fd9-11e9-9199-7bbc374ab027.png">
</details>

### Summary

The problem exists. It is there for a long time and it is still not resolved.
Now i have this problem reproduced with a `thumbnail` filter. With a `fixed-size` filters, this problem **does not** reproduce.
I use CentOS 7.6.1810 (latest), [PHP 7.2.14 (latest)](http://php.net/releases/), [GD 2.2.5 (latest)](https://libgd.github.io/).

### Docker

Surprisingly, this problem does not reproduce in the Docker on Windows.

```Dockerfile
FROM php:7.2-fpm-stretch

RUN apt-get update; apt-get install -y --no-install-recommends openssl git

# GD
RUN apt-get install -y --no-install-recommends libgd-dev; \
    docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/; \
    docker-php-ext-install gd
```

```
# php -v
PHP 7.2.13 (cli) (built: Dec 10 2018 14:32:47) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.13, Copyright (c) 1999-2018, by Zend Technologies
```

```
# php --ri gd

gd

GD Support => enabled
GD Version => bundled (2.1.0 compatible)
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.6.3
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 6b
PNG Support => enabled
libPNG Version => 1.6.28
WBMP Support => enabled
XBM Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1
```

**Comment by robfrawley** [comment] 2019-02-19 08:45
Within this bundle, _all image transform operations_ or, more accurately, the **vast majority** of them, (specifically all image transformation operations that directly manipulate the image data), _are **not** handled by any code within this project_. Instead, this project _**delegates** those operations to an external and **separate project**_.

_What and where is this so-called external project that handles the heavy work of image tranformations?_ It is the excellent [`avalanche123/Imagine`](https://github.com/avalanche123/Imagine) library, which we require in our [composer.json dependency listing](https://github.com/liip/LiipImagineBundle/blob/master/composer.json#L22) with a version constraint of `^0.7.1,<0.8`.

__Given the aformentioned information, two important and quick tests may help in revealing the next steps required to resolve this issue (assuming you have the time and drive to do so):__

1. Check the [`avalanche123/Imagine`](https://github.com/avalanche123/Imagine) library for newer releases/versions (anything more-recent than the current version constraints: `^0.7.1,<0.8`). If they do have a newer release available, force a newer version of [`avalanche123/Imagine`](https://github.com/avalanche123/Imagine) for your application, by locally editing this projects compser constraints, or by using an alias in your local application constraints, or by any other means such that composer can resolve the dependencies and utalize the new [`avalanche123/Imagine`](https://github.com/avalanche123/Imagine) release.

    Next, simply re-run the reproeduction steps (as you did above) with this new dependency version and check if the problem persists or is resolved. **If the problem persists**, _stop reading here and skip down to the next list item (2)_. **If it resolves your issue**, _then issue a fix to this project with a PR_ by adjusting the [composer.json dependency listing version constrain](https://github.com/liip/LiipImagineBundle/blob/master/composer.json#L22) for [`avalanche123/Imagine`](https://github.com/avalanche123/Imagine) to allow the new, working version (taking great care to ensure the new version constraint retains backward compatibility with any previously allowed versions, so as to not break dependencies for those who rely on a specific release of the [`avalanche123/Imagine`](https://github.com/avalanche123/Imagine) library).

2. _If the issue is not fixed by using newer [`avalanche123/Imagine`](https://github.com/avalanche123/Imagine) releases, then the next step is to locate the issue in that external project_. Clone that external library locally and, using the images that pose an issue, make calls directly to that project's API to perform the same operations as detailed in your previouse posts.

    The `avalanche123/Imagine` project has excellent documentation on Read the Docs ([imagine.readthedocs.io/en/stable/](https://imagine.readthedocs.io/en/stable/)) and you can also just look into the [relivant filters](https://github.com/liip/LiipImagineBundle/tree/master/Imagine/Filter) _within this project_ to determine _what calls we are making to the [`avalanche123/Imagine`](https://github.com/avalanche123/Imagine) library_. For example, in [AutoRotateFilterLoader](https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Filter/Loader/AutoRotateFilterLoader.php) there are only two external calls:

    - ```php
          /*
           * @what: \Imagine\Image\ImageInterface::rotate()
           * @link: https://github.com/avalanche123/Imagine/blob/develop/src/Image/ImageInterface.php
           */
          $image->rotate($degree);
      ```
    - ```php
          /*
           * @what: \Imagine\Image\ImageInterface::flipHorizontally()
           * @link: https://github.com/avalanche123/Imagine/blob/develop/src/Image/ImageInterface.php
           */
          $image->flipHorizontally();
      ```

    Once you reproduce the issue with direct calls to the [`avalanche123/Imagine`](https://github.com/avalanche123/Imagine) library, you can then isolate and fix any issues they have in that project. All changes should obviously be tracked and submitted through PR to their repository [https://github.com/avalanche123/Imagine](https://github.com/avalanche123/Imagine), not ours.

Hope this helps and gets your on your way; feel free to ask any question if any arise.

**Closed** 2021-10-06 07:24 UTC
